### ISSUE TITLE
It doesn't work for me (Chrome, Safari)

### ISSUE THREAD

**Issue by andreapavoni** [meenie/8bit.js#15]
Tried the online demo and cloned the repo to try the example locally. But I always get this error in JS console of my browser:

```
Error: 'undefined' is not a function (evaluating 'p.createGain()')
```

Tried with Safari and Chrome.

**Comment by meenie** [comment]
So the only demo is working? But when you clone the repo and run it locally it's not?

**Comment by andreapavoni** [comment]
It never worked for me. I tried online, then locally just to figure out if it works in some way :-(

The error I've posted is the same (both online and locally).

**Comment by meenie** [comment]
Are you on a Mac? Also, which version of Chrome are you using? Version 29?

**Comment by andreapavoni** [comment]
Yes, I'm on a Mac. Chrome version is `29.0.1547.57`

**Comment by meenie** [comment]
Hmm...This is the first report I've heard about a Mac not being able to play the music. I'm guessing more people have had the issue but never reported?  The Web Audio API is actually still in experimental development so there may be bugs.  Could you try running this code in your console to see if it generates a sound?

``` javascript
var ac = new window.webkitAudioContext;
var o = ac.createOscillator()
o.connect(ac.destination);
o.frequency.value = 440;
o.start(0);
o.stop(ac.currentTime + 1);
```

**It may be a little loud, so watch your volume.**

**Comment by andreapavoni** [comment]
Sorry, it was my (big) fault. Today it worked on Chrome (both online and locally). I tried it last week and it didn't worked on Chrome.

closing issue. thanks for your immediate help. I'll continue to watch this project, looks very promising.

**Comment by meenie** [comment]
No worries, have a great day :).
